### ISSUE TITLE
Chrome 'Zoom' feature makes the generated initials too small

### ISSUE THREAD

**Issue by glasscubes** [MatthewCallis/avatar#11]
If you go to your homepage and reduce the zoom to say 90% and then reload your page you will see the initials avatar is not rendering correctly. See attached
![screen shot 2016-09-16 at 15 06 03](https://cloud.githubusercontent.com/assets/5802777/18588682/65a24778-7c1f-11e6-8151-3ac151752940.png)

**Comment by MatthewCallis** [comment]
Thanks for reporting this! I will look into it ASAP.

**Comment by MatthewCallis** [comment]
Looks like its the `window.devicePixelRatio`, I will add a check to make sure this is never < 1.

**Comment by MatthewCallis** [comment]
Fixed! Thanks!
