### ISSUE TITLE
jQuery plugin broken in master

### ISSUE THREAD

**Issue by mwynholds** [MatthewCallis/avatar#12]
When using this library with the jQuery plugin, you are passing in the jQuery wrapped element in to the constructor of `Avatar`.  You should be passing the raw DOM element.  When generating initials, the function calls `this.element.width` and `this.element.height`, which are numbers on DOM elements, but are functions on jQuery wrapped elements.

You probably just need to pass `this[0]` to `Avatar` instead of `this` on line 169.

**Comment by MatthewCallis** [comment]
Somehow completely missed this, will also fix this if I hadn't already. Thanks for reporting it, I don't use it anywhere 👍🏼
