### ISSUE TITLE
Allow option to select either secure or insecure URL for avatars.io to resolve Mixed Content warnings.

### ISSUE THREAD

**Issue by ronaldporch** [MatthewCallis/avatar#13]
Our team is using this in SSL and are getting Mixed Content warnings due to avatars.io being called over an insecure URL (Line 144 on avatar.js). Would be awesome if we could pass in an option to use either 'https://' or 'http://' if possible.

**Comment by MatthewCallis** [comment]
@ronaldporch I can add this, I will try to get to it this week!

**Comment by stealthybox** [comment]
Thanks @MatthewCallis !
Is there any reason to not use https all of the time?
Curious if adding an option is actually needed.

**Comment by MatthewCallis** [comment]
@stealthybox no, I would probably default to `https` unless they actually accept `http` without a redirect.

**Comment by ronaldporch** [comment]
@MatthewCallis made a PR changing http to https. Let me know if you'd like to make any other changes on it.

**Comment by MatthewCallis** [comment]
@ronaldporch approved and merged, will cut a release at lunch. Thanks for the PR! <3
