### ISSUE TITLE
Current version doesn't support IE11

### ISSUE THREAD

**Issue by sunknudsen** [MatthewCallis/avatar#18]
Adding IE11 support appears to be very easy.

It is achieved by replacing the `Object.assign` call found  [here](https://github.com/MatthewCallis/avatar/blob/master/src/avatar.browser.js#L11) by a call to the following ponyfill.

This ponyfill is inspired by the following [polyfill](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign) by Mozilla.

```
function objectAssign(target, varArgs) {
  if (target == null) {
    throw new TypeError('Cannot convert undefined or null to object');
  }
  var to = Object(target);
  for (var index = 1; index < arguments.length; index++) {
    var nextSource = arguments[index];
    if (nextSource != null) {
      for (var nextKey in nextSource) {
        if (Object.prototype.hasOwnProperty.call(nextSource, nextKey)) {
          to[nextKey] = nextSource[nextKey];
        }
      }
    }
  }
  return to;
}
```

**Comment by sunknudsen** [comment]
Thanks Matthew

**Comment by MatthewCallis** [comment]
The new version uses spread and should work fine in IE11 since it went through Babel!

**Comment by sunknudsen** [comment]
Thanks @MatthewCallis. I confirm version 4.0.0 works in IE 11. Good work!
