### ISSUE TITLE
What type of element should I apply the avatar to?

### ISSUE THREAD

**Issue by oddjones** [MatthewCallis/avatar#2]
It doesn't mention anywhere in the documentation what type of HTML element I should start with - I put a bunch of &lt;div class="avatar"&gt;&lt;/div&gt; elements into my page and put this just before my &lt;/body&gt; tag

$( document ).ready(function() {
    $('.avatar').avatar({
  'useGravatar': false,
  'initials': 'MC'
  });

but nothing happened - am I missing something?

**Comment by MatthewCallis** [comment]
It is used on `<img/>` elements, it will display either the gravatar image or a canvas converted to an image representation.
