### ISSUE TITLE
Initials avatar image is not built for hidden angularjs elements 

### ISSUE THREAD

**Issue by atfornes** [MatthewCallis/avatar#5]
I am using avatars in an AngularJS web app.

I am having problems when trying to create an avatar in a hidden element: the src of the image is set to "data:," instead of "data:\<the real data here\>".

I have created a plunkr with an example showing the problem: 
http://plnkr.co/edit/KezYPFfA6JPIFeUepays?p=preview

when clicking toggle visibility button, the wrong avatar is displayed (80x80 image without data)

the expected avatar can be correctly obtained changing line 5 of the app.js file as follows:

chage ```$scope.hidden = true;``` to ```$scope.hidden = false;```

Can you please tell me if I am doing something wrong, or if this is in fact a bug?

Thanks!

**Comment by atfornes** [comment]
I am seeing now that the plunkr example shows the problem in Chromium but not in Firefox, where the avatar is in both cases wrong.

**Comment by MatthewCallis** [comment]
I'll investigate when I get to work and hopefully we can setup a test case and get this fixed!

**Comment by atfornes** [comment]
Great! thank you

**Comment by MatthewCallis** [comment]
@atfornes I found the issue and have a fix and test case ready, I will try and get that out today :hibiscus:

**Comment by MatthewCallis** [comment]
Okay this should be fixed in v1.3.0, let me know if it is still causing trouble.

**Comment by atfornes** [comment]
Wow! that was quick. Thanks a lot! :smiley:
