### ISSUE TITLE
Remove 404 error from console

### ISSUE THREAD

**Issue by BenJBailey** [MatthewCallis/avatar#8]
When using the following options, I get a 404 for each image in the console:

```
{
 'useGravatar': true,
 'size': 20,
 'initials': 'bb',
 'initial_fg': '#B4B7BA',
 'initial_bg': '#FFFFFF',
 'initial_font_family': 'Roboto, Helvetica, sans-serif',
 'hash': 'hashWouldBeHere',
 'email': 'emailWouldBeHere',
 'fallback': 'blank' ,
 'rating': 'pg',
 'forcedefault': false,
 'allowGravatarFallback': false               
}
``` 

A 404 error is thrown in the console for every gravatar image that doesn't exist. While I imagine this 404 is probably needed for the library to detect a missing gravatar, would it be possible to try/catch the error as it's not actually an error in the application (it's working as expected)?

Here's what is returned in the console: 
<img width="542" alt="screen shot 2016-08-02 at 10 02 48 am" src="https://cloud.githubusercontent.com/assets/5232044/17333511/5526f89e-5898-11e6-9f34-d39e65668e3c.png">

**Comment by MatthewCallis** [comment]
Sorry I missed this somehow. Unfortunately even in a try catch block this would still show up in the browse console, I tried to fix before 😿
http://stackoverflow.com/questions/7035466/check-if-file-exists-but-prevent-404-error-in-console-from-showing-up
